// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Room struct {
	ID          int64
	Code        string
	CreatedAt   pgtype.Timestamptz
	OwnerToken  string
	LastEmptyAt pgtype.Timestamptz
	Name        string
}

type RoomApprovedGuest struct {
	RoomCode   string
	GuestToken string
	ApprovedAt pgtype.Timestamptz
}
