// Code generated by sqlc. DO NOT EDIT.

package db

import "context"

const createRoom = `-- name: CreateRoom :one
INSERT INTO rooms (code)
VALUES ($1)
RETURNING id, code, created_at
`

func (q *Queries) CreateRoom(ctx context.Context, code string) (Room, error) {
	row := q.db.QueryRow(ctx, createRoom, code)
	var room Room
	err := row.Scan(&room.ID, &room.Code, &room.CreatedAt)
	return room, err
}

const findRoomByCode = `-- name: FindRoomByCode :one
SELECT id, code, created_at
FROM rooms
WHERE code = $1
`

func (q *Queries) FindRoomByCode(ctx context.Context, code string) (Room, error) {
	row := q.db.QueryRow(ctx, findRoomByCode, code)
	var room Room
	err := row.Scan(&room.ID, &room.Code, &room.CreatedAt)
	return room, err
}
